export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  VAT_TEAM_LEAD = 'VAT_TEAM_LEAD',
  VAT_TEAM_MEMBER = 'VAT_TEAM_MEMBER',
  COMPANY_ADMIN = 'COMPANY_ADMIN',
  COMPANY_USER = 'COMPANY_USER',
  ACCOUNTANT = 'ACCOUNTANT',
  VIEWER = 'VIEWER',
}

export enum EntityStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  PENDING = 'PENDING',
  ARCHIVED = 'ARCHIVED',
}

export enum SubmissionStage {
  DATA_COLLECTION = 'DATA_COLLECTION',
  DOCUMENT_PREPARATION = 'DOCUMENT_PREPARATION',
  REVIEW = 'REVIEW',
  IRD_SUBMISSION = 'IRD_SUBMISSION',
  PAYMENT = 'PAYMENT',
  ACKNOWLEDGMENT = 'ACKNOWLEDGMENT',
  FILING = 'FILING',
  CLOSED = 'CLOSED',
}

export enum VATScheduleType {
  SCHEDULE_01 = 'SCHEDULE_01',
  SCHEDULE_02 = 'SCHEDULE_02',
  SCHEDULE_03 = 'SCHEDULE_03',
  SCHEDULE_04 = 'SCHEDULE_04',
  SCHEDULE_05 = 'SCHEDULE_05',
  SCHEDULE_06 = 'SCHEDULE_06',
  SCHEDULE_07 = 'SCHEDULE_07',
  SCHEDULE_01_AMENDMENT = 'SCHEDULE_01_AMENDMENT',
  SCHEDULE_02_AMENDMENT = 'SCHEDULE_02_AMENDMENT',
  SCHEDULE_03_AMENDMENT = 'SCHEDULE_03_AMENDMENT',
  SCHEDULE_04_AMENDMENT = 'SCHEDULE_04_AMENDMENT',
  SCHEDULE_05_AMENDMENT = 'SCHEDULE_05_AMENDMENT',
  SCHEDULE_06_AMENDMENT = 'SCHEDULE_06_AMENDMENT',
  SCHEDULE_07_AMENDMENT = 'SCHEDULE_07_AMENDMENT',
}

export enum TransactionType {
  LOCAL_SUPPLY = 'LOCAL_SUPPLY',
  IMPORT = 'IMPORT',
  EXPORT = 'EXPORT',
  LOCAL_PURCHASE = 'LOCAL_PURCHASE',
  ZERO_RATED = 'ZERO_RATED',
  EXEMPT = 'EXEMPT',
}

export enum NotificationType {
  EMAIL = 'EMAIL',
  IN_APP = 'IN_APP',
}

export enum FileUploadStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum MappingSystemType {
  QUICKBOOKS = 'QUICKBOOKS',
  XERO = 'XERO',
  TALLY = 'TALLY',
  CLEARTAX = 'CLEARTAX',
  ZOHO = 'ZOHO',
  CUSTOM = 'CUSTOM',
}

export enum TwoFactorMethod {
  EMAIL_OTP = 'EMAIL_OTP',
  TOTP = 'TOTP',
}
